### ISSUE TITLE
KeyError: 'UserResource.patch'

### ISSUE THREAD

**Issue by chriamue** [briancappello/flask-unchained#2]
```bash
pip install git+https://github.com/briancappello/flask-unchained
flask new project testproj # y to all
cd testproj/
pip install -r requirements-dev.txt
pip install marshmallow-sqlalchemy==0.14.1
flask run
```
Bundles Config:
```
BUNDLES = [
    'flask_unchained.bundles.api',
    'flask_unchained.bundles.mail',
    'flask_unchained.bundles.celery',  # move before mail to send emails synchronously
    'flask_unchained.bundles.security',
    'flask_unchained.bundles.session',
    'flask_unchained.bundles.sqlalchemy',
    'flask_unchained.bundles.webpack',

    'app',  # your app bundle *must* be last
]
```

Opening localhost:5000 in browser throws following:
```bash
flask run
 * Environment: development
 * Debug mode: on
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-607-828
127.0.0.1 - - [18/Nov/2018 10:17:36] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask_unchained/bundles/api/__init__.py", line 62, in register_model_resources
    api.register_model_resource(resource)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask_unchained/bundles/api/extensions/api.py", line 123, in register_model_resource
    route = unchained.controller_bundle.controller_endpoints[key]
KeyError: 'UserResource.patch'
```

**Comment by briancappello** [comment]
Hey, I just pushed up a commit to master that should hopefully fix this error
