### ISSUE TITLE
no such table: flask_sessions

### ISSUE THREAD

**Issue by chriamue** [briancappello/flask-unchained#3]
With and without
```
class Config(AppBundleConfig):
SQLALCHEMY_DATABASE_URI = 'sqlite:///db/flaskr.sqlite'
```
in file app/config.py
```bash
127.0.0.1 - - [18/Nov/2018 16:35:46] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 1833, in finalize_request
    response = self.process_response(response)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask/app.py", line 2114, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/flask_session/sessions.py", line 535, in save_session
    session_id=store_id).first()
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2895, in first
    ret = list(self[0:1])
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2687, in __getitem__
    return list(res)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/home/chriamue/temp/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: flask_sessions [SQL: 'SELECT flask_sessions.id AS flask_sessions_id, flask_sessions.session_id AS flask_sessions_session_id, flask_sessions.data AS flask_sessions_data, flask_sessions.expiry AS flask_sessions_expiry, flask_sessions.created_at AS flask_sessions_created_at, flask_sessions.updated_at AS flask_sessions_updated_at \nFROM flask_sessions \nWHERE flask_sessions.session_id = ?\n LIMIT ? OFFSET ?'] [parameters: ('session:31d9ead7-138a-4d50-be58-2f2c8d54a8f2', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)
```

I tried flask db init, but didn't help.
db/flaskr.sqlite is generated but empty.

**Comment by briancappello** [comment]
Ah yes, that needs to be documented. The steps you need to perform migrations are:
```bash
flask db init  # creates the folder structure, but does nothing else
flask db migrate -m 'create initial tables'  # auto-generates a migration for the difference between your app's models and the state of the database
flask db upgrade  # actually runs the migrations
```
